live_config_reload = true

[font]
size = 24.0

[font.normal]
# family = "Classic Console Neue"
# family = "SpaceMono Nerd Font Mono"
# family = "SpaceMono"
family = "Agave Nerd Font"
style = "Bold"

[font.italic]
family = "Agave Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Agave Nerd Font"
style = "Bold"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.45
startup_mode = "Maximized"

[mouse]
hide_when_typing = true
