live_config_reload = true

[font]
size = 12.0

[font.normal]
# family = "Classic Console Neue"
# family = "SpaceMono Nerd Font Mono"
family = "SpaceMono Nerd Font"
style = "Bold"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"
